/**
 * Creating a sidebar enables you to:
 - Create an ordered group of docs
 - Render a sidebar in the docs sidebars.

 * You can extend this functionality by creating a file full of sidebar items
 * Learn more at https://docusaurus.io/docs/sidebar#sidebar-create-a-sidebar-from-a-file
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{
    type: 'autogenerated',
    dirName: '.'
  }],
};

module.exports = sidebars;
